application:
  # 项目名称
  name: KTP

  # 上传文件的路径
  profile: /Users/zhenwen/MyProjects/ClassPle-Vue/classple/file

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 150MB

  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages

  profiles:
    active: druid

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10s

server:
  port: 8080

mybatis:
  type-aliases-package: com.zhenwen.domain
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

